### ISSUE TITLE
Adding Mac OS Support

### ISSUE THREAD

**Issue by FearGannicus** [Seo-Rii/electron-acrylic-window#10]
I don't personally use MacOS, but it would be good for people who are making cross platform applications to have this feature, or something relatively close to the acrylic style.

**Comment by xanderfrangos** [comment]
Actually, this module appears to be modeled after the existing "vibrancy" support in Electron: https://www.electronjs.org/docs/api/browser-window#winsetvibrancytype-macos

So MacOS support isn't needed.

**Comment by Seo-Rii** [comment]
That's right, macOS supports the vibrancy option on the Electron itself. If this module is used in the same way as Windows in macOS, it is already processed to call the Electron built-in function without building the C module.
