### ISSUE TITLE
Installing NPM Module fails

### ISSUE THREAD

**Issue by rmcproductions** [Seo-Rii/electron-acrylic-window#15]
Hello, 

I was just trying to install your module via `npm i -S electron-acrylic-window`. however, while in the building process, npm fails to build the module with the following error message:
```
..\src\main.cc(38): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [E:\MY_PATH\node_modules\electron-acry
lic-window\build\vibrancy-wrapper.vcxproj]
..\src\main.cc(39): error C3861: 'IsWindows10OrGreater': identifier not found [E:\MY_PATH\node_modules\electron-acrylic-window\build\vibrancy-wrapper.vcx 
proj]
..\src\main.cc(89): error C3861: 'IsWindows10OrGreater': identifier not found [E:\MY_PATH\node_modules\electron-acrylic-window\build\vibrancy-wrapper.vcx 
proj]
```

My Windows version is Windows 10 2004, Build 19041.264, and I am using NodeJS v10.16.0 withnpm v6.9.0. Is there anything I can do to fix this / am I missing something?

**Comment by Seo-Rii** [comment]
Please refer to this link and try again: https://github.com/nodejs/node-gyp#installation
If it's still not built, please tell me again.

**Comment by rmcproductions** [comment]
So i **did** forget something!! Well that's embarassing. Sorry for bothering and thanks for your help anyways <3

**Comment by DarkPreacher** [comment]
I have exactly the same issue, followed installation process, option 1, although node-gyp worked fine before. Updated Python to 3.8.5. Nothing changed.
Windows v.1909, build 18363.1016, NodeJS v.14.8.0, node-gyp v.5.1.0

**Comment by Seo-Rii** [comment]
@DarkPreacher This can occur when the path of the project is not an ASCII character. It's good idea to check it out.

**Comment by DarkPreacher** [comment]
There are no non-ASCII chars in project path, it is `D:\_opens\domains\electron\test\electron-acrylic-window\`
Here is error message I get:
```
..\src\main.cc(38): warning C4530: C++ exception handler used, but unwind semantics
are not enabled. Specify /EHsc [D:\_opens\domains\electron\test\electron-acrylic-win dow\build\vibrancy-wrapper.vcxproj]
..\src\main.cc(39): error C3861: 'IsWindows10OrGreater': identifier not found [D:\_o pens\domains\electron\test\electron-acrylic-window\build\vibrancy-wrapper.vcxproj]
..\src\main.cc(89): error C3861: 'IsWindows10OrGreater': identifier not found [D:\_o pens\domains\electron\test\electron-acrylic-window\build\vibrancy-wrapper.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\_opens\domains\electron\test\electron-acrylic-window
gyp ERR! node -v v14.8.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-acrylic-window@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-acrylic-window@0.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by Seo-Rii** [comment]
I have figured out the cause of this problem. The c++ portion of this module uses versionhelper.h to determine the version of Windows, but under certain circumstances (your case) versionelper.h may be included in the path to Windows 8.1 sdk, but this header file does not contain the isWindows10orGreater function used to check the version. In fact, I thought it would be safer to check the version once in js wrapper and one more in C++, so I wrote it like this, but I didn't know this would happen. I will solve this problem next update.

**Comment by Seo-Rii** [comment]
Resolved on faa5423!

**Comment by Seo-Rii** [comment]
This modification has been applied to v0.3.3!

**Comment by DarkPreacher** [comment]
Yep, works perfectly fine now, thank you!
