### ISSUE TITLE
Delay when Resizing window

### ISSUE THREAD

**Issue by R3MOTE-GOD** [Seo-Rii/electron-acrylic-window#26]
Hey everyone, was wondering if you have noticed the extreme lag when resizing a window on the latest 0.4.4 version?

**Comment by Seo-Rii** [comment]
In fact, there has been a lot of effort to address this issue (#6) and is now somewhat better. However, you may still feel that it is not natural. Could you tell me the version of Windows you are using? I'll test it on that version.

**Comment by R3MOTE-GOD** [comment]
> In fact, there has been a lot of effort to address this issue (#6) and is now somewhat better. However, you may still feel that it is not natural. Could you tell me the version of Windows you are using? I'll test it on that version.

Currently on version 20H2

**Comment by R3MOTE-GOD** [comment]
@Seo-Rii After doing some testing it seems that when I run the application with dual monitors there's a lot of delay when resizing the window, however, on my laptop the program runs perfectly fine resizing and everything. 

Is there dual monitor support? Each monitor I have has a different refresh rate (one has 240Hz and the other 60Hz)

**Comment by Seo-Rii** [comment]
Perhaps in that case, the window will refresh with a frequency of 240 Hz because it updates the window based on the frame rate of the higher monitor. This is a lag because it puts a lot of load on the system.
I will modify the maximum refresh rate in the next version, but if you are in a hurry, try adjusting the maximumRefreshRate option. This will also work well on high injection rate monitors such as 240 Hz, as it forces a maximum refresh rate.

+Sorry for the late reply. I didn't care about the answer because I was busy recently.

**Comment by Seo-Rii** [comment]
@R3MOTE-GOD Please test with newly commited version.

**Comment by R3MOTE-GOD** [comment]
> @R3MOTE-GOD Please test with newly commited version.

@Seo-Rii I still seem to have the delay

**Comment by Seo-Rii** [comment]
@R3MOTE-GOD So the only solution that's available right now is to set 'effect' to 'blur' :( I'm sorry about this, but I understand this problem appears in almost all non-UWP apps that have set effect to 'acrylic'. I'll try to find another solution, but I can't guarantee it can be solved. I'm so sorry.

**Comment by R3MOTE-GOD** [comment]
@Seo-Rii Hmm okay, I just tested the blur effect and you're right. Why is this an issue? Does acrylic not have the same amounts of support?

**Comment by Seo-Rii** [comment]
This program uses setwindowcomposition api to implement effects, and it is in RS4 version that acrylic effects have been added. I don't know if it's an optimization problem or Microsoft's intention not to use undocumented api, but from the 19h1 version, it started to lag when it gave an acrylic effect. Other acrylic effect-giving programs are experiencing the same problem. [Like this.](https://github.com/EYHN/vscode-vibrancy/issues/5)

**Comment by R3MOTE-GOD** [comment]
Ahhh @Seo-Rii I understand, I will add a setting to change the effect option in my application for the meantime. Hopefully we find a fix for this in the future :)

**Comment by Seo-Rii** [comment]
@R3MOTE-GOD I found interesting thing. [link](https://github.com/microsoft/ProjectReunion)
Microsoft is working on a project called WinUI 3, which will formally acrylic the windows without using the trick setcompositionattribute. Currently, the project is beta, so it is difficult to apply it to the module, but the result is said to be loaded into the upcoming Windows. If WinUI 3 is formally introduced, the API is expected to be used to solve this problem and many other problems.

**Comment by tscpp** [comment]
I was experiencing lag too, so I switched to `vibrancy: { useCustomWindowRefreshMethod: true }` and the lag was gone.
