### ISSUE TITLE
no disableOnBlur transition effect

### ISSUE THREAD

**Issue by FearGannicus** [Seo-Rii/electron-acrylic-window#27]
I've noticed that the `disableOnBlur` effect automatically changes the colour, which is great, but there's no transition like other UWP or native windows 10 applications.

Is there a reason that this wasn't added? Would this be hard to implement?

**Comment by Seo-Rii** [comment]
That's a good idea! I'll start developing.

**Comment by Seo-Rii** [comment]
Added on d13660d!
