### ISSUE TITLE
Blurry Text

### ISSUE THREAD

**Issue by R3MOTE-GOD** [Seo-Rii/electron-acrylic-window#29]
I've also noticed while developing my application that the text on the electron window looks blurry, I read off of the [electron documentation](https://github.com/electron/electron/blob/master/docs/faq.md#the-font-looks-blurry-what-is-this-and-what-can-i-do) that this is caused due to `sub-pixel rendering` being `off`. 

The documentation recommends to add a background color to the main electron window, but due to the acrylic effect, we need to set the background to transparent correct? Is there a way to combat this? I can live with the blurriness, but I won't lie it is a little annoying for my eyes that there's a slight blur.

**Comment by R3MOTE-GOD** [comment]
Just thought I'd add a screenshot to show the differences between the `sub-pixel rendering` in google chrome, and then without in the electron application. 

![image](https://user-images.githubusercontent.com/55330243/93717365-52dfca00-fb43-11ea-84dd-ace9b4f02883.png)

**Comment by Seo-Rii** [comment]
In fact, I didn't notice the bug when I was using the module. As you mentioned, sub-pixel antialiasing is impossible when Windows is transparent or semi-transparent. [Link](https://github.com/electron/electron/blob/master/docs/faq.md#the-font-looks-blurry-what-is-this-and-what-can-i-do) However, looking for a method, it is said that disabling hardware acceleration can solve the problem. [Link](https://github.com/electron/electron/issues/8708#issuecomment-632807756) But I can't check the blurs even in the basic state, so can you check them for me?

First, put ```app.disableHardwareAcceleration()``` at the top of the app and test it. Must be inserted directly below require ('electron'). If this works, add an ```app.commandLine.appendSwitch("in-process-gpu")``` below upper code and check it again.

**Comment by R3MOTE-GOD** [comment]
@Seo-Rii I didn't notice any changes to the antialiasing, however the application did use about 50 less MB of Memory. Sadly I assume this is something that wont be fixed? Kinda makes all our applications look terrible if we can't make the text displayed in it crisp.

**Comment by Seo-Rii** [comment]
```-webkit-font-smoothing: subpixel-antialized;``` add this to CSS and please try again.

**Comment by xanderfrangos** [comment]
This is an Electron thing. Having a non-white background (ex. transparent) changes how text is rendered. See: https://github.com/electron/electron/issues/10025

I don't believe this is something that can be fixed while also using Acrylic blur with Electron.

**Comment by Seo-Rii** [comment]
@R3MOTE-GOD  As @xanderfrangos mentioned, it's hard to find a way to correct the blurry text at the moment. Therefore, I will not consider this issue until the electron corrects the bug, so I will close this issue. I'm sorry about this.
