### ISSUE TITLE
Watch out for this potentially breaking line of code!

### ISSUE THREAD

**Issue by AryToNeX** [Seo-Rii/electron-acrylic-window#3]
https://github.com/04SeoHyun/electron-acrylic-window/blob/3b09c3f02742006dbe7cccc7a8051cccd8568f3d/index.js#L26

Wrapping `BrowserWindow` is mostly fine, however, stuff will break when Electron tries to cast wrapped `BrowserWindow` objects into `NativeWindow` (in its C/C++ code).
As far as I can tell, this breaks every child window that may spawn from a wrapped `BrowserWindow`, especially system dialogs and modals.

Please consider spawning a new Electron `BrowserWindow` object and returning that object in the constructor. You can always add your methods to it via `Object.defineProperty()` like it happens here:
https://github.com/AryToNeX/Glasstron/blob/ccfa06e09b615c2620999a906f99202d9a06eebc/src/browser_window.js#L56-L61

Then, this method can be used like so
https://github.com/AryToNeX/Glasstron/blob/ccfa06e09b615c2620999a906f99202d9a06eebc/src/browser_window.js#L33-L34

---

On an unrelated note, did you notice the slow mouse polling rate when dragging and resizing windows in Windows 10 v1903+?

**Comment by 04SeoHyun** [comment]
Thank you for reporting the bug! I haven't tested a lot with this library yet, so I wasn't even thinking about it. I will fix it in the next release.
<hr/>
Yes, I know about this problem. I'm trying to figure out why it's slowing down.

**Comment by Seo-Rii** [comment]
I've been so busy lately that I couldn't care less about this issue. We will correct this issue as soon as possible (probably within a month). I'm sorry again.

**Comment by Seo-Rii** [comment]
+I found out why they react slowly to the mouse. The reason will go up, but since we use ACCENT_ENABLE_ACRYLICBLURBEHIND in the SetWindowCompositionAttribute API, which can be used from RS4, it responds faster to input. Originally, this program was using the ACCENT_ENABLE_BLURBEHIND option. Perhaps the next version will apply this amendment. Thank you.

**Comment by Seo-Rii** [comment]
Finally, I applied this fix on https://github.com/Seo-Rii/electron-acrylic-window/commit/45605c10911d411d5f1c9a810eed78de1f417119. Thanks for waiting!
