### ISSUE TITLE
Window loses acrylic effect after opening devTools

### ISSUE THREAD

**Issue by tscpp** [Seo-Rii/electron-acrylic-window#33]
I'm using the wrapper class.
```typescript
function createWindow() {
	const window = new BrowserWindow({
		icon: path.join(__dirname, 'icons/explorer.ico'),
		frame: false,
		vibrancy: {
			disableOnBlur: false,
			effect: 'acrylic',
			theme: 'appearance-based',
			useCustomWindowRefreshMethod: true
		},
		webPreferences: {
			nodeIntegration: true,
			enableRemoteModule: true
		},
		minWidth: 250,
		minHeight: 250
	})
	
	window.loadFile(path.join(__dirname, '../web/window.html'))

	return window
}
```

### Before (VSCode in the background)
![image](https://user-images.githubusercontent.com/47453366/97080711-c327b280-15fd-11eb-95c6-b0b67dcba306.png)
### DevTools open (the effect gets completly white)
![image](https://user-images.githubusercontent.com/47453366/97080764-20236880-15fe-11eb-839f-5ed349235afd.png)
### After (the window loses it's effect)
![image](https://user-images.githubusercontent.com/47453366/97080714-cc188400-15fd-11eb-847a-6d404518ebf5.png)

**Comment by Seo-Rii** [comment]
Please try with ```mainWindow.webContents.openDevTools ({mode: "detach"});```.

**Comment by tscpp** [comment]
Thank you!
This is not a huge deal. Thus a normal user would never start dev tools; a restart of the window fixes it.

**Comment by tscpp** [comment]
Weird, the same thing still occurs...

**Comment by Seo-Rii** [comment]
When the above code is applied, the devTool must be opened in a new window separate from the BrowserWindow. Isn't it?

**Comment by tscpp** [comment]
Yes, the window is attached, but the window loses its effect after closing dev tools.

**Comment by Seo-Rii** [comment]
While devtools was open, no method was found to enable the Blur effect, but it was modified to re-appear the Blur effect after it was closed.
However, I still recommend opening devtools in a separate window.
