### ISSUE TITLE
Movement lag and random aero shake triggering

### ISSUE THREAD

**Issue by tscpp** [Seo-Rii/electron-acrylic-window#34]
## Movement lag

Whatever `useCustomWindowRefreshMethod` is set to the window lags behind the cursor when moving the window slowly.

<sub>_The movement lag is more severe due to the screen recorder._</sub>
[![](https://github.com/tscpp/storage/raw/main/file.gif)](https://github.com/tscpp/storage/raw/main/file.gif)

## Aero shake trigger

The aero shake triggers randomly when moving the window around in one direction and not shaking it.

<sub>_The area shake triggering is more severe due to the screen recorder_</sub>
![file](https://user-images.githubusercontent.com/47453366/97087282-4e6a6d80-1629-11eb-9f51-f7db44da0d10.gif)

**Comment by Seo-Rii** [comment]
APIs that apply blurs in the current window work very slowly. My contributors and I have redefined the effects of movement, sizing and aero to solve this problem. The result of it is useCustomWindowRefreshMethod. However, it still leads to some performance degradation, which I don't think can be solved at the moment. I'm so sorry.
