### ISSUE TITLE
Merge this to Electron!

### ISSUE THREAD

**Issue by adel-sbeh** [Seo-Rii/electron-acrylic-window#37]
I suggest making a pull request to integrate this feature to Electron. This module is pretty stable.
https://github.com/electron/electron/issues/3002#issuecomment-716506824

**Comment by Seo-Rii** [comment]
Thank you for your high regard for this module. However, this module still lacks a lot. Also, there are still many things to do, such as typographical porting. Therefore, I will consider this proposal later. Thank you.
