### ISSUE TITLE
Option for using ACCENT_ENABLE_ACRYLICBLURBEHIND or ACCENT_ENABLE_BLURBEHIND

### ISSUE THREAD

**Issue by tscpp** [Seo-Rii/electron-acrylic-window#39]
I noticed using ACCENT_ENABLE_BLURBEHIND the window doesn't lag at all **and** the effect is different though very similar. There should be an option for using blur- or acrylicblurbehind.

**Comment by Seo-Rii** [comment]
This module already has an option. Applying the effect option 'blur' applies ACCENT_ENABLE_BLURBEHIND.

**Comment by tscpp** [comment]
I forgot...
