### ISSUE TITLE
Win10 window refresh lag

### ISSUE THREAD

**Issue by tscpp** [Seo-Rii/electron-acrylic-window#40]
https://github.com/sourcechord/FluentWPF/blob/b70731c6d026b2087dbf41656ff53854d48813d8/FluentWPF/Utility/AcrylicHelper.cs#L62

> In Windows10 1903 or later, if you use `ACCENT_ENABLE_ACRYLICBLURBEHIND`, it will not follow the mouse operation by dragging and moving the window.
> 
> Do not use `ACCENT_ENABLE_ACRYLICBLURBEHIND` until the behavior of the `SetWindowCompositionAttribute` function is fixed.

**Comment by Seo-Rii** [comment]
Yes, this is a bug in Windows. We introduced win10refresh.ts to minimize this bug.

**Comment by tscpp** [comment]
The win10refresh has some issues moving the window. Either the win10refresh should be fixed or temporary use the blur-behind filter.

**Comment by tscpp** [comment]
Maybe [WinUI 3 Preview 2](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/) could be used?

**Comment by tscpp** [comment]
WinUI 3 is unfortunately not available as a c++ library for windows because it's made with XAML.

**Comment by tscpp** [comment]
As of the WinUI 3 release, it can be used with win32, directx and native c++: https://microsoft.github.io/microsoft-ui-xaml/about.html#controls
