### ISSUE TITLE
I can't install the latest version

### ISSUE THREAD

**Issue by adel-sbeh** [Seo-Rii/electron-acrylic-window#41]
![Administrator_ Windows PowerShell 11_13_2020 5_36_21 PM](https://user-images.githubusercontent.com/72353925/99090114-e0391b00-25d6-11eb-92f7-53463c717e3d.png)
![Administrator_ Windows PowerShell 11_13_2020 5_36_24 PM](https://user-images.githubusercontent.com/72353925/99090122-e29b7500-25d6-11eb-9380-53251db11e73.png)

**Comment by adel-sbeh** [comment]
I tried to uninstall and reinstall the module. But it didn't work.

**Comment by adel-sbeh** [comment]
Never mind! I had to install TypeScript:
```
npm install typescript -g
```

**Comment by tscpp** [comment]
Reopen this. Older versions of npm doesn't support using `tsc` without calling it with `npx tsc` if it's not installed globally, which shouldn't be a requirement. This should be fixed in package.json.

**Comment by Seo-Rii** [comment]
@tscpp Resolved on 1c8598e. Thank you for reporting!
