### ISSUE TITLE
Window blur latency

### ISSUE THREAD

**Issue by adel-sbeh** [Seo-Rii/electron-acrylic-window#43]
I'm using the latest version of Windows 10 (20H2)

https://streamable.com/e/ev8vps?autoplay=1

----
###### Edit by @tscpp

https://user-images.githubusercontent.com/47453366/126036357-6e92b814-e21f-46c7-b6cd-56a9f662dbcf.mp4

**Comment by tscpp** [comment]
This is an error in electron (too). If you have VS Code, Discord, Slack, try to resize the window quickly and notice the resize latency.

**Comment by adel-sbeh** [comment]
No, I'm not talking about the normal resize glitch.

**Comment by tscpp** [comment]
Unfortunately, we can do nothing about this except increasing the maximum refresh rate with the current API Windows 10 is offering. You can do this by using the property in options. Set it to maybe 60 or 144.

**Comment by Seo-Rii** [comment]
We've been discussing this issue for a long time, but we couldn't find a solution. :(

**Comment by R3MOTE-GOD** [comment]
@Seo-Rii I looked into this quite a lot myself and noticed that WIndows 10 is redoing a lot of their API. Most likely this could be something they fix in the future with new releases of Win-UI 3.

**Comment by tscpp** [comment]
I tried to get Win-UI 3 preview 2 to work without VS19s Windows 10 Desktop Development tool, but it's not possible. It's needed to make a separate project using the Windows 10 Desktop Development tool and package it to an `.exe` file and run it as a child_process with cli arguments.

**Comment by Seo-Rii** [comment]
Bugs related to window drag delays will be discussed in #69 in the future. I'll close the issue.
