### ISSUE TITLE
inherting from electron.BrowserWindow not allowed

### ISSUE THREAD

**Issue by GauravKnight** [Seo-Rii/electron-acrylic-window#44]
class BrowserWindow extends electron.BrowserWindow {
                              ^

TypeError: Class extends value undefined is not a constructor or null

https://stackoverflow.com/questions/50130888/error-when-extending-from-browserwindow-electron-class

**Comment by tscpp** [comment]
Thank you for reporting this issue. I have looked at the sources, at it seems correct. Have you encountered this bug?

**Comment by GauravKnight** [comment]
Yes, I was surprised at first and tried to workaround the issue but nothing seems to work.
I even tried to run with different version of electron to no avail.

**Comment by tscpp** [comment]
Can you make a repository so I can recreate it?

**Comment by GauravKnight** [comment]
Please close this the issue has seemingly been fixed on a new machine
