### ISSUE TITLE
Some drag issues cased by the custom window refresh function.

### ISSUE THREAD

**Issue by aleversn** [Seo-Rii/electron-acrylic-window#51]
1. The window occurs a bounce effect when I drag the window quickly and then released the mouse button.

https://user-images.githubusercontent.com/30100324/104563035-1f8df180-5684-11eb-974a-ba3090413555.mp4

The GIF is displayed in 0.5x.

2. The window movement occurs a delay when released the mouse button, and the pointer is outside the window.
![2](https://user-images.githubusercontent.com/30100324/104564516-f4a49d00-5685-11eb-87a3-d0f6b215b41f.gif)

3. The restore the window, it is displayed in the wrong position when dragged the window to maximize and the mouse button where the pointer is outside the window.
![3](https://user-images.githubusercontent.com/30100324/104564529-f8382400-5685-11eb-8b29-e0f1ea6581d7.gif)

**Comment by tscpp** [comment]
This is known common issues with our custom Windows 10 refresh function. You can try turn it off using `useCustomWindowRefreshMethod: false`, but this will introduce new issues.

#40 - Win10 window refresh lag
https://github.com/Seo-Rii/electron-acrylic-window/blob/master/src/win10refresh.ts

**Comment by aleversn** [comment]
Yes, but when I turn off the function, the window moved very slow when dragging.

**Comment by rendomnet** [comment]
Same here. Window moves very slow

**Comment by tscpp** [comment]
@rendomnet 

If you turn off `useCustomWindowRefreshMethod` performance degradation is expected. Do not turn off `useCustomWindowRefreshMethod` without decreasing `maximumRefreshRate` vastly. Try using `effect: blur` and see if it helps.

<table><tr><td>

https://github.com/Seo-Rii/electron-acrylic-window#options

- `useCustomWindowRefreshMethod` - Boolean (optional)

Use custom window resize/move handler for performance. Default is true.

Special thanks to @djsweet and @xanderfrangos.

> This is an experimental feature. May cause errors.

</td><tr></table>

The blur amout is specified by `SetWindowCompositionAttribute` in `user32.dll`. There is nothing we can do about this for now.

**Comment by tscpp** [comment]
You can specify alpha using custom `theme` property, e.g. `#00000055`.

**Comment by rendomnet** [comment]
@tscpp  it is slow unusable with **useCustomWindowRefreshMethod**  and without it.
only **effect blur** fixes lag, but blur is too weak.

**Comment by tscpp** [comment]
@rendomnet can you send a screenshot and possibly a video?

**Comment by xanderfrangos** [comment]
@tscpp I believe @rendomnet is referring to the Windows 7 legacy `blur` option, which does improve performance but doesn't look anything like the `acrylic` option. Unfortunately, `useCustomWindowRefreshMethod` is a buggy re-implementation of native window handling. It still needs a lot of work and dances around a ton of Windows and Electron-related bugs. Unless someone wants to take another stab at that, you have to pick your poison. This is the only "acrylic" module for Electron that does more than point `SetWindowCompositionAttribute` at Electron and call it a day.

**Comment by rendomnet** [comment]
Maybe we can optionally switch to blur when moving or resizing window?

**Comment by tscpp** [comment]
@rendomnet until the custom refresh method is stable, that would be a great idea. I'll start working on it asap.

**Comment by Seo-Rii** [comment]
Bugs related to window drag delays will be discussed in #69 in the future. I'll close the issue.
