### ISSUE TITLE
Notice about maintenance

### ISSUE THREAD

**Issue by Seo-Rii** [Seo-Rii/electron-acrylic-window#57]
**First of all, this is not a notice of discontinuation of development of this module, so feel free to read the content.**

I'm sorry that I couldn't answer or take appropriate action even though there have been many issues recently. This is because I am about to take the college entrance exam. Therefore, development of this module will not be possible until December this year. I'm so sorry about this. I'll come back as soon as possible. Thank you.

**Comment by tscpp** [comment]
If you would like, I could help with patches and maintaining the package as well as package versioning. I am currently maintaining my own packages (e.g. [kolint](https://www.npmjs.com/package/knockout-lint)) as of this moment. I use this package myself and I would be happy to help.

**Comment by Seo-Rii** [comment]
@tscpp Thank you for your continued interest in this module! I sent you an invitation email for the collaborator, so please check it out.

**Comment by tscpp** [comment]
@Seo-Rii can discussions be enabled for this repo?

**Comment by Seo-Rii** [comment]
@tscpp I enabled it.
