### ISSUE TITLE
error with test program

### ISSUE THREAD

**Issue by mirkokral** [Seo-Rii/electron-acrylic-window#60]
Hi, i have a problem, whenever i want to run the test i get this following error
![image](https://user-images.githubusercontent.com/75212488/125496121-8bcbf9a5-7fc7-4be3-a829-b3d3cc75f575.png)

Can you please help me

**Comment by tscpp** [comment]
The test script does not build the C++. You will have to run the build script before testing. I am not sure if the gyp build is intentionally excluded from the test script. I'll experiment with the scripts to see if any improvements can be done later.

```
npm run build
```
