### ISSUE TITLE
option to disable blur effect

### ISSUE THREAD

**Issue by rendomnet** [Seo-Rii/electron-acrylic-window#64]
for example `effect: off`
sometimes it is needed to disable blur even when app is focused.

**Comment by tscpp** [comment]
I am not entirely sure what you mean by an option. If you want to toggle the vibrancy, use the "setVibrancy" function. Is there something I am missing?

**Comment by tscpp** [comment]
Why would that be necessary? If "setVibrancy" is called with null the vibrancy effect with be removed.
