### ISSUE TITLE
backdrop-filter: blur not working

### ISSUE THREAD

**Issue by AidasPa** [Seo-Rii/electron-acrylic-window#65]
Whenever I don't have an opaque background color on my body the backdrop-filter does not render properly:

![image](https://user-images.githubusercontent.com/40808754/130493138-1bdb58dc-2a4b-4755-b5da-7564c49db4c0.png)

![image](https://user-images.githubusercontent.com/40808754/130493168-d3dd5961-d61b-4cb2-8224-0331260575f3.png)

**Comment by tscpp** [comment]
Unfortunately, there is nothing we can do about this. Possibly when (and if) the project is updated to use winui3. The browser is not aware of the acrylic effect and will treat the background as if it were transparent.

**Comment by AidasPa** [comment]
Ahh, understood.
Cheers for the fast reply!

**Comment by tscpp** [comment]
I tried this myself and did not get the same result. Can you link a reproduction so I can check it out?

<sup>I could not get a video to work</sup>
![image](https://user-images.githubusercontent.com/47453366/130495470-5be21896-b66b-4b15-abb3-f0b75720f5dd.png)

**Comment by AidasPa** [comment]
https://github.com/AidasPa/backdrop-filter-rendering

Here's how it should look (with approximately the same background colors)
![image](https://user-images.githubusercontent.com/40808754/130499352-bc28c43e-054f-40a4-a946-e3b2adfaa80e.png)

and how it looks with vibrancy *(comment out the body background-color in the repo)*
![image](https://user-images.githubusercontent.com/40808754/130499444-8eb37b3b-7739-4416-9f8a-2d8d701beb05.png)


Here's a really close issue which I have found (solves by setting a background color - which we can't do because vibrancy)

https://github.com/electron/electron/issues/30077

**Comment by tscpp** [comment]
Sorry for the late response. I'd say this can not be fixed by electron-acrylic-window and is an electron issue; there is nothing we can do. Maybe you could use a "virtual background" behind the element using the closest solid color to the window. Feel free to reopen if you have any questions.
