### ISSUE TITLE
[Bug] Using Thumbar buttons on Acrylic windows causes them to not appear.

### ISSUE THREAD

**Issue by cryptofyre** [Seo-Rii/electron-acrylic-window#66]
Pretty self explanatory but using electron-acrylic-window breaks the [thumb-bar controls](https://www.electronjs.org/docs/api/structures/thumbar-button) and causes them not to appear but they appear just fine with it disabled.

Broken (With EAC):
![image](https://user-images.githubusercontent.com/33162551/131271185-bd40f864-6442-45a3-90da-2a17bb0ce532.png)

Working (No EAC):
![image](https://user-images.githubusercontent.com/33162551/131271202-2b35a159-adc6-465d-a416-71c50e4fbadf.png)

**Comment by coredev-uk** [comment]
Solved - was the result of the window not being shown in time
