### ISSUE TITLE
Window overflow in Windows 11

### ISSUE THREAD

**Issue by Akwd22** [Seo-Rii/electron-acrylic-window#71]
Hello,

There is a bug with this module in Windows 11, which makes the bottom of the window overflows above the taskbar, and the left-side of the window overflows into the second monitor. Without your module, with vanilla Electron, everything works fine.

With this module, vibrancy enabled:
![with_vibrancy](https://user-images.githubusercontent.com/60796682/136675281-343e7aee-5ee6-4849-ac5b-915883b9af4f.png)

Without this module, vanilla Electron:
![without_vibrancy](https://user-images.githubusercontent.com/60796682/136675292-0dec53bc-8cbb-473c-a8cf-d5fbf0df9647.png)

**Comment by Akwd22** [comment]
Yes, but the overflow above the taskbar is a new bug that appeared in Windows 11.

**Comment by Seo-Rii** [comment]
This is the same bug as in Windows 10. It's just that this bug was not shown in Windows 10 because the size of the task bar was different.
