### ISSUE TITLE
Window gets shrunk to the minimum size when dragging

### ISSUE THREAD

**Issue by craftzdog** [Seo-Rii/electron-acrylic-window#76]
Hi,

Thanks for the great module!
It works great, but from Electron from 12.0.4 to 12.2.1, the issue started happening.
When dragging a window with the acrylic effect, it always gets resized into the minimum size.
It still happens on Electron 16.0.4 with `electron-acrylic-window@0.5.11`.
I confirmed it happens both on Windows 10 and 11.
Could you look into it?

Thanks in advance!

**Comment by tscpp** [comment]
I am unable to reproduce this issue. Can you create a minimum repository with steps to reproduce the issue. Thanks!

**Comment by Seo-Rii** [comment]
I also can't reproduce the bug. I would appreciate it if you could upload the test repo.

**Comment by craftzdog** [comment]
Here: https://github.com/craftzdog/electron-acrylic-window-drag-issue-reproduction

**Comment by craftzdog** [comment]
I found that it only happens on a virtual machine on Parallels.
It was happening on both a physical machine and a virtual machine on Electron 12.2.1.
But after upgrading it to 16.0.4, looks like it's been resolved on the physical machine.
Maybe it could still cause the same issue in the future, but I close it for now.
