### ISSUE TITLE
[Request] Set Acrylic Color

### ISSUE THREAD

**Issue by xanderfrangos** [Seo-Rii/electron-acrylic-window#8]
Could you add the option for passing through an RGBA hex color with `setVibrancy` to set the Acrylic tint? I'm having a hard time getting the exact colors I need with the default. I'd do a PR, but I'm no good with C++. 😅

I figure it would be something like `window.setVibrancy("custom", 0xCC123456)`. Or just `window.setVibrancy(0xCC123456)` if you're checking types.

Thanks!

**Comment by Seo-Rii** [comment]
I also once tried to add an option to change the color of acrylic, but the color did not change properly due to an error that I did not know why. If I solve the problem or someone tells me how to fix it, I will apply the improvements immediately.

**Comment by xanderfrangos** [comment]
@Seo-Rii You may have run into the colors being interpreted in little-endian as ABGR instead of RGBA. So if you wanted the RGBA color `0x11223344`, it needs to be sent to SetWindowCompositionAttribute as `0x44332211`. [Source](https://withinrafael.com/2018/02/02/adding-acrylic-blur-to-your-windows-10-apps-redstone-4-desktop-apps/)

**Comment by Seo-Rii** [comment]
@xanderfrangos I found what was the problem. The color was changing properly, but the transparency was too low to confirm. 😅

**Comment by Seo-Rii** [comment]
Now you can set the color with giving RGBA hex code into op parameter! https://github.com/Seo-Rii/electron-acrylic-window/commit/29754fffb429d8874a397580eac890aff798d5fb
