### ISSUE TITLE
The acrylic effect disappears when I minimize the window

### ISSUE THREAD

**Issue by paologiua** [Seo-Rii/electron-acrylic-window#83]
As the title suggests, the acrylic effect stops working during the window minimization animation.

https://user-images.githubusercontent.com/46423764/149554809-ae27a538-772f-49a8-b9aa-a39a6cd124bf.mp4

**Comment by tscpp** [comment]
Windows legacy APIs is used to apply the acrylic effect to the window, however this API is fairly limited. The filter cannot follow the window animations (I think) and will only update according to the window position. I think the effect is also missing in the task view, not sure though.

**Comment by paologiua** [comment]
It would be perfect if it had a non transparent background (and the acrylic effect disabled) before the window was minimized. It would be useful to have a listener that detects when the window is about to minimize, but unfortunately I have not found any. win.on('minimize', callback) of electron triggers when the window is already minimized.
